# dependencies
markdown: redcarpet
pygments: true

# permalinks
permalink: none

# server
destination: _site
exclude: ["_site", ".gitignore", ".htaccess", "bower.json", "CNAME", "Gruntfile.js", "package.json", "node_modules", "README.md", "vagrant", ".vagrant", "old", "src"]

# site variables
name: 'MUJIN'

# first one here is the default language
languages: ["ja", "en", "ja"]
